### ISSUE TITLE
utils.build_vocab() TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by 1615070057** [intfloat/commonsense-rc#10]
data = None, so 'NoneType' object is not iterable,i think shouild be a parameter passed into build_vocab.
Thank you!

**Comment by intfloat** [comment]
Can you share more details on this issue?

`build_vocab` loads dictionary from the disk by default, so there is no need to pass `data` argument. If you wish to build dictionary from scratch, you can delete all vocabulary files under `./data/` and then call `build_vocab` with a `data` argument.
