### ISSUE TITLE
first preprocess dataset or conceptnet?

### ISSUE THREAD

**Issue by nijianmo** [intfloat/commonsense-rc#3]
Hi YuanFuDao team, thanks for sharing this wonderful work! 

I have one question about preprocessing. It seems that:
1- when preprocess dataset, it needs to compute the relation (via compute_feature) from a _**preprocessed**_ conceptnet
2- when preprocess conceptnet, it needs the vocab (via build_vocab) built from a _**preprocessed**_ dataset.

This becomes the "egg comes first or chicken comes first" problem... Is there anything I'm missing here? It would be great if you could point out my mistake or give a more detailed description about how to preprocess.

Thanks!

**Comment by intfloat** [comment]
Oops! 

You are right, I precomputed the vocabulary at the very early stage of this project and then just assume they already exist.

Sorry for the trouble, I'll fix this issue soon.

**Comment by nijianmo** [comment]
Thanks for the quick response! 

BTW, it only has an assertion in utils.py for the rel_vocab; however, there should be some code to build the rel_vocab. 
```
# Load conceptnet relation vocabulary
    assert os.path.exists('./data/rel_vocab')
```

Hope you can fix these soon. Meanwhile I will first try a model without conceptnet part. Thanks!

**Comment by intfloat** [comment]
I fixed this issue in commit https://github.com/intfloat/commonsense-rc/commit/3eade5cd1a6a2679ce57bc4f60fd918679e54217 and updated  `README.md` and `run.sh`, now you can check out `run.sh` to preprocess the dataset and train the model.

As to the `./data/rel_vocab`, I added the shell command to generate this file in commit https://github.com/intfloat/commonsense-rc/commit/7865c72d9ce64d96eb4effb05b832e0aebb29439.

Thank you.

**Comment by nijianmo** [comment]
Awesome! Thanks for the super quick response.

Two last questions. To process RACE dataset. Just need to run another script including "preprocess_race_dataset('./data/RACE/')" after
```
python3 src/preprocess.py conceptnet
python3 src/preprocess.py
```
right?

For preprocessing RACE, it's using the same **vocab** built from the SemEval dataset, which is **kind of small**. Is there any logic behind this?

Thank you!

**Comment by intfloat** [comment]
Yes, I used `preprocess_race_dataset` function for preprocessing RACE dataset.

I also merged two vocabularies based on RACE(only frequent words) and SemEval dataset into one vocabulary, which is `./data/vocab` in this repository.  I kind of lost track of that part of the code, hopefully you can implement by yourself.

Thank you.

**Comment by nijianmo** [comment]
I see, you do merge these two. Thanks for this information! I think simply run "build_vocab_from_raw_dataset" on RACE and then merge it with SemEval's vocab is fine. 

Thank you!

**Comment by Borororo** [comment]
Hi, 
The vocab file you given contains the  vocabularies from both RACE and SEMEVAL datasets, right?
Since I can only generate 12717 vocabs from SEMEVAL dataset.
