### ISSUE TITLE
Train on rice

### ISSUE THREAD

**Issue by idealwhite** [intfloat/commonsense-rc#6]
Hi, I really appreciate your job! Could you give some instructions on how to process and train model on RACE dataset?

**Comment by intfloat** [comment]
Thank you for your interests.

Both RACE dataset and SemEval-2018 Task 10 dataset are multiple-choice reading comprehension datasets. All you need to do is to preprocess RACE dataset into the same format as required by this repository. You can check out [src/preprocess.py preprocess_race_dataset](https://github.com/intfloat/commonsense-rc/blob/master/src/preprocess.py#L284) for reference.

Be cautious that RACE dataset is much larger and takes longer time to train.

**Comment by idealwhite** [comment]
THanks for your reply, it works well!
