### ISSUE TITLE
How to predict？

### ISSUE THREAD

**Issue by Jasperty** [intfloat/commonsense-rc#7]
run.sh only gives how to train, but no hint that how to predict and get the predict json

**Comment by intfloat** [comment]
Please check out src/play_with_trained_model.py , simply run

```
python3 src/play_with_trained_model.py --pretrained /path/to/model --test_mode True
```

to predict on test set.

**Comment by wazzy** [comment]
After training successfully and getting Dev accuracy around 0.830617. On running play_with_trained_model.py shows me dev accuracy: 0.511262.

**Comment by intfloat** [comment]
You probably miss the groundtruth labels in test data, please check out `./data/test-data-processed.json` and see if the `label` is `-1`.

The most convenient way is to submit the prediction file to Codalab to see the evaluation results on test data.

**Comment by wazzy** [comment]
I checked the test data, and I didn't missed out the groundtruth labels, i tried with groundtruth labels as well as -1, when i make it -1 I get accuracy as 0.
How do I predict on newer data?

**Comment by wazzy** [comment]
I see the codelab way of evaluation giving better accuracy.
Thanks for that.
How can I test the model on new dataset ??
