### ISSUE TITLE
Ablation Study  相关问题

### ISSUE THREAD

**Issue by sf774966129** [intfloat/commonsense-rc#8]
作者你好，
        能问问在Ablation Study这一步，是否需要在去掉相应模块后重新训练一个模型？
        还是直接在完整的已经训练好的模型上，修改或者删除 train.py 文件中各个模块的代码？

**Comment by intfloat** [comment]
需要去掉相应模块重新训练一个，这样能更准确反映ablation study的结果

**Comment by sf774966129** [comment]
好的。  谢谢了！
